name: CICD Docker
on:
	push:
		branches:
			- master
jobs:
	build-push:
		runs-on: ubuntu-latest
		steps:
      - name: List of files
			  run: ls -la
      - name: Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
			- uses: actions/checkout@v3
			- name: Run unit test
				run: pnpm test