name: CICD Docker
on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: List of files
        run: ls -la
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - name: Run pnpm install
        run: pnpm install
      - name: Run unit test
        run: pnpm test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build/-push-action@v5
        with:
          push: true
          tags: gigihsigap/backend-nestjs-image:${{ github.run_number }}
      - name: Check docker images
        run: docker image ls
